DROP TABLE IF EXISTS recipe;
CREATE TABLE IF NOT EXISTS recipe (
  id SERIAL PRIMARY KEY,
  mealsname VARCHAR(255),
  category VARCHAR(255),
  area VARCHAR(255),
  instruction TEXT,
  imageurl VARCHAR(255),
  youtube VARCHAR(255),
  noin1 TEXT,
  noin2 TEXT,
  noin3 TEXT,
  noin4 TEXT,
  noin5 TEXT,
  noin6 TEXT,
  noin7 TEXT,
  noin8 TEXT,
  noin9 TEXT,
  noin10 TEXT,
  noin11 TEXT,
  noin12 TEXT,
  noin13 TEXT,
  noin14 TEXT,
  noin15 TEXT,
  noin16 TEXT,
  noin17 TEXT,
  noin18 TEXT,
  noin19 TEXT,
  noin20 TEXT,
  nome1 TEXT,
  nome2 TEXT,
  nome3 TEXT,
  nome4 TEXT,
  nome5 TEXT,
  nome6 TEXT,
  nome7 TEXT,
  nome8 TEXT,
  nome9 TEXT,
  nome10 TEXT,
  nome11 TEXT,
  nome12 TEXT,
  nome13 TEXT,
  nome14 TEXT,
  nome15 TEXT,
  nome16 TEXT,
  nome17 TEXT,
  nome18 TEXT,
  nome19 TEXT,
  nome20 TEXT
);

